### ISSUE TITLE
Show Power Point plus/minus in Token Action HUD

### ISSUE THREAD

**Issue by steveculshaw** [mrcomac/token-action-hud-swade#10]
**Is your feature request related to a problem? Please describe.**
The old Token Action HUD had a section under Power Points allowing you to easily add/subtract Power Points 

![image](https://github.com/mrcomac/token-action-hud-swade/assets/64320/2f4cdf54-aed8-4dac-8fdf-a3e618253dd7)

**Describe the solution you'd like**
It would be really useful to replicated this into the new Token Action HUD SWADE modules.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

Additional context
OS: [Windows 11]
Token Action HUD: [1.4.9]
Token Action HUD SWADE: [0.6.1]
Swade System: [3.0.4]
Foundry VTT: [11.302]
Browser: [Google Chrome 114.0.5735.134]
Other modules: BR2

**Comment by Vogliadicone** [comment]
Thanks, that worked. BUT, what Power Poinbt Pool are you refering too? I have a sorcerer with 25PP coming from the AB Sorcery. In the Token Action HUD he sees 10 PP, not his 25PP. Is there one option, where I can specify the typoe of PP? I didn't found one...

- Token Action HUD Core: 1.4.11
- Token Action HUD SWADE: 0.7.0
- Swade System: 3.0.4
- Foundry VTT: 11.304
- Browser: Google Chrome

**Comment by steveculshaw** [comment]
@mrcomac Updated to v0.7.0, but I'm not seeing anything w.r.t. token power points?

Does something need to be activated?

**Comment by mrcomac** [comment]
@steveculshaw you need to reset the HUD. Go to the hud config and reset it. After that it should work

**Comment by mrcomac** [comment]
Never mind. Let me double check it.

**Comment by steveculshaw** [comment]
@mrcomac 
Something weird going on. 
My GM account will NOT show the new options, tried reset HUD multiple times, but no joy
<img width="460" alt="image" src="https://github.com/mrcomac/token-action-hud-swade/assets/64320/5414c5b1-6c30-4fc9-b2f0-8bba92cafde4">

Created a second GM account, logged in using an anonymous browser session, and the new HUD options are showing...
<img width="204" alt="image" src="https://github.com/mrcomac/token-action-hud-swade/assets/64320/65932ba6-e799-4cd5-a5c7-23be552f7de3">

**Comment by Vogliadicone** [comment]
@steveculshaw Have you tried the "Reset HUD" option in the module options? It helped in my case.
![HUD](https://github.com/mrcomac/token-action-hud-swade/assets/119852651/4aa2ea25-fc70-4673-a53c-a26582bf44ed)

**Comment by steveculshaw** [comment]
Ah ha ... ta
