### ISSUE TITLE
Show Statuses in Token Action HUD

### ISSUE THREAD

**Issue by steveculshaw** [mrcomac/token-action-hud-swade#11]
**Is your feature request related to a problem? Please describe.**
The old Token Action HUD had a section Status which allowed you to easily add/subtract various Statuses, i.e. Shaken, Distracted, Vulnerable, Stunned, Entangled, Bound and Incapacitated.

![image](https://github.com/mrcomac/token-action-hud-swade/assets/64320/f002164a-2dfa-4b54-bc14-240ae4da141a)

**Describe the solution you'd like**
It would be really useful to replicated this functionality into the new Token Action HUD SWADE module.
Even better would be showing all of the tokens current statuses, to allow ease of removing, e.g. Prone, Flying, etc.

**Describe alternatives you've considered**
N/A

**Additional context**
OS: [Windows 11]
Token Action HUD: [1.4.9]
Token Action HUD SWADE: [0.6.1]
Swade System: [3.0.4]
Foundry VTT: [11.302]
Browser: [Google Chrome 114.0.5735.134]
Other modules: BR2

**Comment by mrcomac** [comment]
Hi @steveculshaw ,

Do you mean remove only option or add and remove statuses?

**Comment by steveculshaw** [comment]
The "classic" version allowed adding/removing the short list showed, and if another condition was already applied, you could remove it.

Ideally the SWADE version would replicate this.

**Comment by mrcomac** [comment]
OK. I have an idea for that. I just need time to code.
This weekend I'll try to delivery the functionalities already available in the classic HUD.

**Comment by steveculshaw** [comment]
Amazing !!!

Many thanks

**Comment by steveculshaw** [comment]
@mrcomac Updated to v0.7.0, but I'm not seeing anything w.r.t. token statuses?

Does something need to be activated?

**Comment by steveculshaw** [comment]
@mrcomac 
Something weird going on. 
My GM account will NOT show the new options, tried reset HUD multiple times, but no joy
<img width="460" alt="image" src="https://github.com/mrcomac/token-action-hud-swade/assets/64320/5414c5b1-6c30-4fc9-b2f0-8bba92cafde4">

Created a second GM account, logged in using an anonymous browser session, and the new HUD options are showing...
<img width="204" alt="image" src="https://github.com/mrcomac/token-action-hud-swade/assets/64320/65932ba6-e799-4cd5-a5c7-23be552f7de3">

**Comment by steveculshaw** [comment]
@mrcomac 
Ignore me ... I read through some of the other issues, and spotted the comment about the difference between Reset HUD (which is in the HUD Core settings) and the Reset Actions (which is in the SWADE HUD bar options)

**Comment by mrcomac** [comment]
Nice,

I need to find a way out to display a message, maybe a diologue box, to tell about the requirement to reset the HUD to be able to see new groups.
