### ISSUE TITLE
[DOCUMENTATION] Add details about the collapse/expand on each HUD sections

### ISSUE THREAD

**Issue by steveculshaw** [mrcomac/token-action-hud-swade#12]
**Is your feature request related to a problem? Please describe.**
The Token Action HUD had a feature to collapse/expand a section, e.g. Powers.
This should be documented.

_... Last night player had problem that they couldn't see their powers ... see first screen shot_
<img width="111" alt="image" src="https://github.com/mrcomac/token-action-hud-swade/assets/64320/51f1e7f6-c8c1-4b5a-a303-0ed3b8228c84">

_... We only realised after head scratching that he's inadvertently managed to collapse them ... see second screen shot_
<img width="313" alt="image" src="https://github.com/mrcomac/token-action-hud-swade/assets/64320/0e82f8a5-29c1-42fc-a5c2-fa448492ab15">

**Describe the solution you'd like**
Documentation on this feature
_... appreciate this is secondary to adding features, but here as an aide-memoire_

**Describe alternatives you've considered**
N/A

**Additional context**
OS: [Windows 11]
Token Action HUD: [1.4.9]
Token Action HUD SWADE: [0.6.1]
Swade System: [3.0.4]
Foundry VTT: [11.302]
Browser: [Google Chrome 114.0.5735.134]
Other modules: BR2

**Comment by elidakirigo** [comment]
hi, I'd like to contribute to the documentation of this project.

**Comment by steveculshaw** [comment]
Ditto ... but not sure how to?

**Comment by elidakirigo** [comment]
yes

**Comment by mrcomac** [comment]
There are 2 options. First one is to change the Readme.md of the repository with a proposal. Also I'm checking how to build a what's new when a new version is installed. 

Feel free to use this issue to give some idea what we do need to cover.

**Comment by elidakirigo** [comment]
thanks @mrcomac

**Comment by mrcomac** [comment]
Doc should mention
- collapse / expand items
- reset token HUD after update to make sure new groups will be displayed
- Edit
- Correlate sheet to HUD

**Comment by Larkinabout** [comment]
There's also a wiki page on the Token Action HUD Core github for some of the core functionality: [How to Use Token Action HUD](https://github.com/Larkinabout/fvtt-token-action-hud-core/wiki/How-to-Use-Token-Action-HUD)

**Comment by mrcomac** [comment]
I'll add it to the readme.md .. it probably will solve this issue
