### ISSUE TITLE
[Minor Bug] Empty "General" section in the "General" section

### ISSUE THREAD

**Issue by Vogliadicone** [mrcomac/token-action-hud-swade#14]
In the "General" section there another "General" section without any content. I can delete it easily, but I think, it could be removed in an update.
![HUD_1](https://github.com/mrcomac/token-action-hud-swade/assets/119852651/6b3a106d-8f64-4151-b813-67b8d224e959)
![HUD_2](https://github.com/mrcomac/token-action-hud-swade/assets/119852651/d60866d1-f587-4043-979f-aaf3eb5e5a6c)

I reseted the Token Action HUD via the "Reset HUD" option after updating to v0.7.2.

- Token Action HUD Core: 1.4.11
- Token Action HUD SWADE: 0.7.2
- Swade System: 3.0.4
- Foundry VTT: 11.304
- Browser: Google Chrome

**Comment by mrcomac** [comment]
i'll keed this open until have all actions added to the hud. This is a future group to include actions that don't fit to other categories.

**Comment by mrcomac** [comment]
next update will remove the general  section

**Comment by mrcomac** [comment]
removed in the version 0.9.4
