### ISSUE TITLE
[Minor Bug] Can't delete "Derived stats" under "Attributes"

### ISSUE THREAD

**Issue by Vogliadicone** [mrcomac/token-action-hud-swade#15]
After I added the "Derived Stats" section to the "Action" section, I tried to delete it under "Attributes", but that didn't work out.

I delete the section here:
![HUD_1](https://github.com/mrcomac/token-action-hud-swade/assets/119852651/0d60b08a-9d7a-4027-a0a7-420e53c9d9a0)
Then I safe the changes:
![HUD_2](https://github.com/mrcomac/token-action-hud-swade/assets/119852651/9fa61e0b-cebc-482e-ac2d-2a6e706e3879)
But when I open the category anew, the "Derived Stats" are back:
![HUD_3](https://github.com/mrcomac/token-action-hud-swade/assets/119852651/6d2929e4-1d9f-4f6c-ac48-70a9f17fb280)

I reseted the Token Action HUD via the "Reset HUD" option after updating to v0.7.2.

- Token Action HUD Core: 1.4.11
- Token Action HUD SWADE: 0.7.2
- Swade System: 3.0.4
- Foundry VTT: 11.304
- Browser: Google Chrome

**Comment by mrcomac** [comment]
it will be resolved on 0.7.6
