### ISSUE TITLE
[Bug] Powers shows non existing Power Points for a character

### ISSUE THREAD

**Issue by Vogliadicone** [mrcomac/token-action-hud-swade#16]
After updating to v0.7.2 all Magix users see "Power Points" for their own and a lot of other pp categories.

Example 1:
A sorcerer with 25pp from Sorcery:
![HUD_2](https://github.com/mrcomac/token-action-hud-swade/assets/119852651/510ea3ae-18aa-4ef5-b4da-a1e62bbe0b34)
The HUD shows pp also for General, Magic, Magic Items, Max & Cleric (Luck) (the character has no magic items with pp):
![HUD_1](https://github.com/mrcomac/token-action-hud-swade/assets/119852651/af37e6d1-f2b7-4995-a2d9-eadc5509a291)

Example 2:
A cleric with 20pp from Cleric (Luck):
![HUD_3](https://github.com/mrcomac/token-action-hud-swade/assets/119852651/e5524c57-3839-44ee-8cbe-5524f3c9ad6c)
The HUD shows pp also for General, Magic, Sorcery, Magic Items & Max (the character has no magic items with pp):
![HUD_4](https://github.com/mrcomac/token-action-hud-swade/assets/119852651/d271e6d7-bb71-4865-8577-f22ed5cb9c63)

Maybe the categories are all somewhere in the game world available pp categories? At least in the scene I took the screenshot from, there are no token that have pp from General, Magic, Magic Items or Max. But maybe somewhere in an compendium (f.e. in Savage Pathfinder) is an item or creature with one of these? Anyway, it's quite irritating, to have 6 categories where the player should only see one.

Let me know, if I can help you with more data.

- Token Action HUD Core: 1.4.11
- Token Action HUD SWADE: 0.7.2 (I reseted the Token Action HUD via the "Reset HUD" option after updating to 0.7.2)
- Swade System: 3.0.4
- Foundry VTT: 11.304
- Browser: Google Chrome

**Comment by Vogliadicone** [comment]
Sure, here you have the two characters from the example above (I had to zip them, since github didn't support the upload of json files):
[2-magic-users.zip](https://github.com/mrcomac/token-action-hud-swade/files/11935465/2-magic-users.zip)

**Comment by mrcomac** [comment]
Thank you, I'll have a look into it next weekend or before it (depends on my workload this week)

**Comment by Vogliadicone** [comment]
Pleae, no stress. I’m just looking into this stuff right now, because I just updated to v11 and my group is in its summer break and therefore I have time for this 😜 Just happy that somebody wrote a module for the new Token HUD.

**Comment by mrcomac** [comment]
Token HUD saves the layout to a file. I need to figure out how to validate if it's an update and reset it programmatically, the problem of thos, it will remove custom config.

**Comment by mrcomac** [comment]
Probably the core hud  has an option to make this with low impact. I need to xheck it.
