### ISSUE TITLE
[Bug] Effects not showing

### ISSUE THREAD

**Issue by steveculshaw** [mrcomac/token-action-hud-swade#17]
**Describe the bug**
The Effects section isn't showing the effects on a character.

<img width="144" alt="image" src="https://github.com/mrcomac/token-action-hud-swade/assets/64320/ff2d69f0-3e00-4389-bed6-be52cd13d318">

And the character ...
<img width="283" alt="image" src="https://github.com/mrcomac/token-action-hud-swade/assets/64320/d6b9987c-69f0-493a-be12-1e2a66b50957">

**Versions:**
OS: [Windows 11]
Token Action HUD: [1.4.11]
Token Action HUD SWADE: [0.7.2]
Swade System: [3.0.4]
Foundry VTT: [11.302]
Browser: [Google Chrome 114.0.5735.134]
Other modules: BR2

**Additional context**
Any additional context.

**Comment by mrcomac** [comment]
Yep,
isn't available yet.. for some reason when we enable or disable effects, the HUD doesn't get updated. It means, the button doesn't change colors like the effects we have in the general section.

**Comment by steveculshaw** [comment]
Ah ha ... ta

**Comment by Larkinabout** [comment]
> Yep, isn't available yet.. for some reason when we enable or disable effects, the HUD doesn't get updated. It means, the button doesn't change colors like the effects we have in the general section.

You might need to trigger a HUD update in your roll handler using `game.tokenActionHud.update()`.

**Comment by mrcomac** [comment]
@Larkinabout i was using  `Hooks.callAll("forceUpdateTokenActionHUD") `but when it calls the update, apparently the variable `isUpdating ` was true.

I've changed to `game.tokenActionHud.update()` and it worked. Maybe I added a wait somewhere that solve the issue. thank you. I'll add this to the next version.

**Comment by Larkinabout** [comment]
That's true, I actually use the hook call in the system modules I maintain, so it should still work. I'll have a look and see if I can figure out why they're acting differently.
