### ISSUE TITLE
[Bug] Some Token don't have a minus button ("-") for Wounds, Fatigue and/or Power Points

### ISSUE THREAD

**Issue by Vogliadicone** [mrcomac/token-action-hud-swade#18]
After updating to v0.7.3 I didn't see the "-" button for Wounds, Fatigue and/or Power Points for some tokens. The status is always the same for a specific token. F.e. my cleric never sees the "-" for Wounds, Fatigue and Power Points:
![HUD_1](https://github.com/mrcomac/token-action-hud-swade/assets/119852651/dc88ad7f-7ff7-4410-b70f-b55e77f52106)
![HUD_2](https://github.com/mrcomac/token-action-hud-swade/assets/119852651/ade343da-c27e-4663-8822-5af5517baf61)
While my sorcerer has the "+" / "-" buttons for Power Points and misses them only for Wounds & Fatigue:
![HUD_3](https://github.com/mrcomac/token-action-hud-swade/assets/119852651/f362f266-2826-4f13-bf5a-4623ac6f19f0)

- Token Action HUD Core: 1.4.11
- Token Action HUD SWADE: 0.7.3 (I reseted the Token Action HUD via the "Reset HUD" option after updating to 0.7.3)
- Swade System: 3.0.4
- Foundry VTT: 11.304
- Browser: Google Chrome

**Comment by mrcomac** [comment]
Hi @Vogliadicone , the powerpoint one is odd.. the fatigue and wounds, since the current value is 0, it will not show the button, as soon as you change to a number bigger than 0, it will show.

**Comment by mrcomac** [comment]
I just saw the error. fix will be available soon.

**Comment by mrcomac** [comment]
v0.7.4
