### ISSUE TITLE
Value Being Updated Directly on Wounds/Fatigue/Power Points

### ISSUE THREAD

**Issue by Larkinabout** [mrcomac/token-action-hud-swade#19]
**Is your feature request related to a problem? Please describe.**
I have another module that logs actor changes to chat and I've noticed that some changes are not logged if made from the HUD. This is because `actor.system[event].value += 1`  in the Roll Handler is updating the value in the actor object directly before the `update` method is called.

**Describe the solution you'd like**
Switch to  `actor.system[event].value + 1`  and `actor.system[event].value - 1` so the values are not updated before the `preUpdateActor` hook.

**Describe alternatives you've considered**
No other alternatives.

**Additional context**
None.

**Comment by mrcomac** [comment]
Goo catch.. it shouldn't include that `=`
