### ISSUE TITLE
BR2 enabled

### ISSUE THREAD

**Issue by grendel111111** [mrcomac/token-action-hud-swade#2]
**Is your feature request related to a problem? Please describe.**
In teh classic HUD there was the option to send  the action to either the SWADE roller or BR2. Was it removed intentionally?

**Describe the solution you'd like**
If possible can we get the option put back in?
![image](https://github.com/mrcomac/token-action-hud-swade/assets/80164119/fa7288de-449b-4a43-b0f1-765bb246a2b0)
![image](https://github.com/mrcomac/token-action-hud-swade/assets/80164119/d7c731ea-5a11-4343-a14b-60dc4c078162)
Thanks

**Comment by mrcomac** [comment]
Hi @grendel111111 

Nah, the next update will have support to br2.

**Comment by mrcomac** [comment]
Task is blocked.

Pending https://github.com/javierriveracastro/betteroll-swade/issues/598

**Comment by mrcomac** [comment]
Support to BR2 is now on test stage (workarround in place for consumables). Feel free to test.

https://github.com/mrcomac/token-action-hud-swade/releases/download/0.6.0-test/module.json
