### ISSUE TITLE
Trying to make attacks from the HUD, some weapons not working properly, others not working at all.

### ISSUE THREAD

**Issue by sroakjp** [mrcomac/token-action-hud-swade#20]
**Describe the bug**
I have a token with 3 melee weapons. One was already there when the issue first appeared, the others I added trying to troubleshoot this issue. If I select the first weapon from the HUD the Better Rolls 2 (BR2) card appears as expected. I'm trying to make a wild attack, so I select that action and press roll. The attack works, but the vulnerable status is not applied. Repeating this, selecting the weapon from the character sheet, and it works as expected. The other two weapons do nothing when selected from the HUD and an error appears in the console.

**Steps to reproduce**
1. Select weapon from HUD
2. If weapon card appears in chat, (no error message)
3. Select Wild Attack
4. Press roll button
5. Notice, no Vulnerable status

Newly added weapon:
1. Select weapon from HUD
2. Nothing happens, error message, see below, appears in browser console.

**Versions:**
- Token Action HUD Core: [e.g. 1.4.13]
- Token Action HUD SWADE: [e.g. 0.7.5]
- Swade System: [e.g. swade 3.0.5]
- Foundry VTT: [e.g. 11.305]
- Browser: [e.g. Google Chrome 114.0.5735.199]

**Additional context**
Error message, for weapons that do nothing
![image](https://github.com/mrcomac/token-action-hud-swade/assets/62338951/30209ab2-1250-4859-b842-9f480e9ea1e2)

Console output for attack that should have applied Vulnerable status but did not (2 images)
![image](https://github.com/mrcomac/token-action-hud-swade/assets/62338951/78da60d4-b72e-4316-907d-392ba452de3e)
![image](https://github.com/mrcomac/token-action-hud-swade/assets/62338951/229bf1c7-9803-4d05-86af-ab7f6bf6d6a2)

**Comment by mrcomac** [comment]
that is a bug.
BR2 is waiting for (token|actor, itemID, collapse_actions)

I need to fix how HUD is calling it within _rollItem()

next release will have a fix.

**Comment by mrcomac** [comment]
Hi @sroakjp 

Version 0.7.6 should address this issue. If issue persists feel free to comment here please.

**Comment by mrcomac** [comment]
It probably isn't resolved yet. Issue #22

**Comment by mrcomac** [comment]
i'm not able to reproduce this issue, i'm assuming after some updates in br2 and the token action hud swade this issue doesn't exist anymore.
please, let me know if it persists in your end.
