### ISSUE TITLE
Better Rolls 2 Support: Rolling From the Token's Actions

### ISSUE THREAD

**Issue by LeBonkerson** [mrcomac/token-action-hud-swade#21]
**Is your feature request related to a problem? Please describe.**
When using the Better Rolls 2 integration for Token Action HUD, the cards that are pulled up are from the token's Actor sheet, instead of the token's sheet itself. This makes keeping track of effects and ammo per token (especially for enemy tokens that are dragged out multiple times per Actor sheet) difficult, since the modifiers like Distracted or ammo spent from RoF weapons aren't applied.

**Describe the solution you'd like**
If possible, I'd like there to be a setting in the module settings where we can choose whether a token's sheet or the token's Actor sheet is used when using Better Rolls 2 support for SWADE.

**Describe alternatives you've considered**
Currently, I've migrated back to Token Action HUD Classic to resolve this temporarily. Opening the sheets manually while using the new Token Action HUD SWADE defeated the purpose of using the module.

**Additional context**

**Comment by mrcomac** [comment]
Hi @LeBonkerson ,

I didn't understand the issue correctly. Tokens doesn't have items, to access them we need to use ``token.actor.items``. However, tokens have effects. The behaviour we will have for a token is related to which option we make when configuring the prototype token of an actor.

Can you confirm the desired behaviour please?

If you link the actor data to the token (image below), and drag multiple tokens to the scene, all effects and damage applied to one token will be replicated to the other ones.

![image](https://github.com/mrcomac/token-action-hud-swade/assets/6748594/93948a52-1c45-4ccb-9fad-096edfadd27f)


If you don't link the actor to the sheet, all effects will be applied to that specifict token and will not be replicated across all tokens within the scene.

is that the desired behaviour?

**Comment by LeBonkerson** [comment]
Apologies for not explaining it well enough. As an example, in the Token Action HUD Classic version, I was able to select a token on the map and choose a piece of its gear to have it do an attack and negatives from effects like Distracted and Wounds would show up. Ammo would also automatically subtract.

Using the new Token Action HUD Core and Token Action HUD SWADE, those negatives do not apply since the HUD pulls from the Actor sheet instead of from each individualized token sheet.

I was able to determine this because after dragging out three enemies, I attempted to set one to Distracted and run an attack, but it didn't have the negative applied using Better Rolls 2. When I applied the Distracted debuff to the Actor sheet, it applied correctly to that Token, but also to every other token. This wasn't the case with the old Token Action HUD Classic, which pulled the Gear from the individual Token and not the referenced Actor.

I may just be confused on the functionality of the new module, so please let me know if I'm mistaken. Thanks so much for all your help!

**Comment by mrcomac** [comment]
Thank you @LeBonkerson for the details.

Version 0.7.6 should address this issue. If issue persists feel free to comment here please.
