### ISSUE TITLE
Weapons with BR2

### ISSUE THREAD

**Issue by Alekboldlin** [mrcomac/token-action-hud-swade#22]
**Describe the bug**
When trying to use weapon from hud with better rolls 2 installed, in chat card shows up, but there is no roll.
Better rolls setting are set as Show card and trait roll. There is a error in console.
Attributes and Skills works fine.

![image](https://github.com/mrcomac/token-action-hud-swade/assets/143077587/e8d27ce4-8d04-499e-89cf-e5a17a910663)
![image](https://github.com/mrcomac/token-action-hud-swade/assets/143077587/215ef5cc-8d22-4e60-b20a-0cb7e080e1aa)

**Steps to reproduce**
1. Add weapon to actor
2. Activate it from hud

**Versions:**
- Token Action HUD Core: [1.4.18]
- Token Action HUD SWADE: [0.7.6]
- Swade System: [swade 3.1.3]
- Foundry VTT: [11.308]
- Browser: [Google Chrome 116.0.5845.111]
- Better Rolls 2 [3.42]
- SWIM [2.1.0]
- socketlib [1.0.13]

**Comment by mrcomac** [comment]
I'll have a look late this week.
Probably I need to call br2 using another function.

**Comment by mrcomac** [comment]
after some updates i can't reproduce this issue, please let me know if this issue persists in your end.

**Comment by Alekboldlin** [comment]
I updated to version 0.8.5 and module isn't loading at all. :(

![image](https://github.com/mrcomac/token-action-hud-swade/assets/143077587/8b84e4db-f14f-4017-b541-1f43c3eded04)

**Comment by Alekboldlin** [comment]
Ok, so weapons are working now.
But every time I roll for skills or attributes benny is also spend, dunno why.
And there is also this wrong name in settings tab.
![image](https://github.com/mrcomac/token-action-hud-swade/assets/143077587/61270ce1-9e0a-4112-b4d5-b5632b30760a)

**Comment by mrcomac** [comment]
I'll test without de dev module and using a char as example I can try fix both issues

**Comment by Alekboldlin** [comment]
I don't know what You mean by char. Character? World? Or something else?

**Comment by Alekboldlin** [comment]
Last patch fixed unmapped tab issue, but there is still spending benny on attributes and skills.
Here You go, exported actor.
[fvtt-Actor-orc-q3FngZpeN8M6jieU.json](https://github.com/mrcomac/token-action-hud-swade/files/13350391/fvtt-Actor-orc-q3FngZpeN8M6jieU.json)

**Comment by mrcomac** [comment]
thanks for the json
please test v0.9.0
it should solve the bennie issue and adds support to AE

**Comment by Alekboldlin** [comment]
Tested it, and everything looks ok.

Btw any chances that we will get feature so when You click button with Shift, Alt or Ctrl it will activate corresponding action?
And support for new action in BR2 called "Show the card and open the action dialog"?

**Comment by mrcomac** [comment]
the button behaviour should already there

![image](https://github.com/mrcomac/token-action-hud-swade/assets/6748594/f5025b89-27fd-45eb-aebf-d0e25408ad2e)

the new option  "Show the card and open the action dialog" i didn't see yet. do you have an example to share?

**Comment by mrcomac** [comment]
oh, i see what you meant.

**Comment by Alekboldlin** [comment]
About button behaviour I meant extra settings in tab so You can configure extra actions.

Now after You set for example Single click action in Token Action HUD SWADE it will always do this action. Doesn't matter if I do LBM click on HUD , Shift+LBM etc. it always do only single click action.

But how about setting so if I press LBM on HUD it will do single click action, if I press Shift+LBM on HUD it will do Shift click action.

**Comment by mrcomac** [comment]
the config works in this way
if you select in the configuration of the HUD "single click action" it will retrieve the behaviour from the "single click action" configured in BR2

If BR2 has selected the option "default system roll" in the "single click action", HUD will adopt this behaviour.

In other words, the hud retrieves the behaviour configured for that option from BR2.

However, the dialog behaviour is something new, it will be available in the next version of this module.

in the future, if you configure BR2 to display the dialog box pressing CTRL, if you go to the config HUD and select to behaviour like CTRL click action, it will display the dialog box.

**Comment by mrcomac** [comment]
to change the behaviour based on the click, like you mentioned, i will need to check how to do it.

**Comment by mrcomac** [comment]
@Alekboldlin are you able to test v0.9.3? it provides the click behaviour.
You can select the default behaviour from the settings (for example, if you want the HUD behaviour to copy some behaviour from BR2, or just pressing CRTL, SHIT or ALT)
