### ISSUE TITLE
Add Edges and Special Abilities to the HUD

### ISSUE THREAD

**Issue by JasonSK22** [mrcomac/token-action-hud-swade#23]
**Is your feature request related to a problem? Please describe.**
No, just a feature request.

**Describe the solution you'd like**
A tab for Edges and Special Abilities from the token's sheet

**Describe alternatives you've considered**
Before the SWADE system got its own Token Hud module I believe that Edges, Hindrances, and Special Abilities were all accessible from the HUD.

**Additional context**
NA

Thanks for your great work.

Jason

**Comment by mrcomac** [comment]
There is no option to turn on/off edges and SA. What I can do is add the effecs within those ones to the effects in the effects tab in a specific category.

there are a couple of options to address it, first one is add all effects and have 2 categories (edges, and special abilities)

another option is to add which edge and SA as a subcategory and the effects in those subcategories.

i'll make a test with option 1.

**Comment by mrcomac** [comment]
available in the v0.7.8

**Comment by JasonSK22** [comment]
Hi, I appreciate that you added active effects display to the token Hud for SWADE. That will be super handy.

My request was to add a tab for edges, Special abilities, and Hindrances to be displayed/listed.  Currently you have to open the character sheet to see what edges, SA, and Hindrances a actor has.  It would be good to be able to see the edges, SA, and Hindrances an actor has from the Hud itself.

**Comment by Neurochimp** [comment]
Hello,

Thought I'd chime in here with a bit of a use-case. One of my players recently took Counterattack. One or two have First Strike. Being able to at a glance see that in the HUD is an invaluable time-saver. For the DM like-wise, I don't have all my Extras & Wildcards memorized. I might miss that certain Extras have First Strike & only catch it midstream while digging into the sheet.

Consider all the Combat Edges that aren't really automated. Having them in the HUD allows a quick cross-reference to see that Extra has a particular Edge. Nothing really to turn off & on but saves steps in opening sheet, going to the tab, etc...

Just my 2 cents. I like a lot of what you've done with the HUD. This might make it more cramped but can help immensely.
