### ISSUE TITLE
Add handling of BR2 click action modifiers

### ISSUE THREAD

**Issue by steveculshaw** [mrcomac/token-action-hud-swade#25]
**Is your feature request related to a problem? Please describe.**
Currently Token Action HUD only supports the default action, i.e. the "Show Better Rolls card"

![module-settings-click-action](https://github.com/mrcomac/token-action-hud-swade/assets/64320/e493f7e7-a9ad-467a-b905-855fd27a3e24)

**Describe the solution you'd like**
Add support for the additional click actions, i.e., click with CTRL, SHIFT or ALT keys pressed.

**Describe alternatives you've considered**
None.

**Additional context**
N/A

**Comment by mrcomac** [comment]
will have a look

**Comment by steveculshaw** [comment]
Many thanks 

> will have a look

**Comment by mrcomac** [comment]
New configuration in version v0.8.0

![Captura de tela 2023-11-06 204158](https://github.com/mrcomac/token-action-hud-swade/assets/6748594/cff98388-aeed-4323-b942-3408c9f2815f)

![Captura de tela 2023-11-06 204257](https://github.com/mrcomac/token-action-hud-swade/assets/6748594/8a686d99-5918-465d-bddb-ad9593507a15)

**Comment by steveculshaw** [comment]
@mrcomac Weird ... I'm not seeing any item for Token Action HUD SWADE in the Configure Game Settings

<img width="152" alt="image" src="https://github.com/mrcomac/token-action-hud-swade/assets/64320/39b9645c-7baf-47c6-b536-1b4ff16c6437">

Foundry v11.313
BR2 v3.56
TAHS v0.8.0

**Comment by steveculshaw** [comment]
@mrcomac Oooh, I'm be on tender hooks waiting for the update :-)

Seriously, many thanks for all the work on a really useful module

**Comment by mrcomac** [comment]
Hi @steveculshaw, thank you

I've raised the v0.8.4 that should add the config feature requested.

Please, feel free to reopen it if you identify any issue.
