### ISSUE TITLE
Cannot remove Vulnerable condition after being Stunned

### ISSUE THREAD

**Issue by carmenbianca** [mrcomac/token-action-hud-swade#26]
**Describe the bug**
It is possible to endlessly toggle and untoggle the Vulnerable condition until you click on the 'Stunned' button in the HUD. After that, it is no longer possible to untoggle the Vulnerable condition for any token until you reload the browser window.

**Steps to reproduce**
1. Select a token.
2. Under 'General' in the HUD, click on 'Stunned'. Vulnerable is automatically toggled on.
3. Click on 'Vulnerable' to untoggle it. Nothing happens.
4. Select another token.
5. Click on 'Vulnerable' in the HUD. It is toggled on.
6. Click on 'Vulnerable' to untoggle it. Nothing happens.
7. Reload browser window.
8. Select one of the two tokens.
9. Click on 'Vulnerable' to untoggle it. Nothing happens.
10. Select _another_ token.
11. Click on 'Vulnerable' twice. It is toggled on, and then toggled off.

**Versions:**
- Token Action HUD Core: 1.4.20
- Token Action HUD SWADE: 0.7.8
- Swade System: 3.1.4
- Foundry VTT: 11 stable 311
- Browser: Firefox 118.0.1

**Additional context**
This bug does not happen if this module is disabled.

**Comment by mrcomac** [comment]
After some tests, i've identified the issue today. Sometimes this module is making wrong updates to the character sheet. I'll need to rework the statuses changes (enable/disable) to fix it.

It will take some time to fix. Please bear with me.

**Comment by carmenbianca** [comment]
No worries. Thank you for your maintainership :rocket:

**Comment by mrcomac** [comment]
this should be resolved in v0.8.5.
please feel free to reopen if  the issue hasn't been resolved.
