### ISSUE TITLE
Does not work with the latest version of Token Action HUD Core

### ISSUE THREAD

**Issue by Deadlander** [mrcomac/token-action-hud-swade#27]
**Describe the bug**
Does not work  with the latest release of Token Action HUD Core
![image](https://github.com/mrcomac/token-action-hud-swade/assets/13036735/d14dd14c-16b5-4c78-b313-ab940cfc6eff)

**Steps to reproduce**
Start the server with it enabled.

**Versions:**
- Token Action HUD Core: 1.5.0
- Token Action HUD SWADE: 0.7.8
- Swade System: 3.2.2
- Foundry VTT: 11.313
- Browser: Chrome

**Additional context**
Any additional context.

**Comment by steveculshaw** [comment]
Just to confirm, I'm getting same error  :-(

**Comment by mrcomac** [comment]
Wow. That's is a high priority issue to fix.
I'll work on this later today.

**Comment by Deadlander** [comment]
Awesome! Thanks!

**Comment by mrcomac** [comment]
A heads up that it's taking longer than I've expected. if you need to use the hud, please downgrade the core module to 1.4

**Comment by steveculshaw** [comment]
Thanks for the heads up,  and for a great module

**Comment by mrcomac** [comment]
v0.7.9 should address this issue. please feel free to reopen if it doesn't.

**Comment by Vogliadicone** [comment]
I’ve got updated to v0.7.9testing. Can’t get to 0.7.9. Is that ok or is there a problem with the update rule?

**Comment by mrcomac** [comment]
those have the same code, but it's odd since i didn't add the testing to foundy.
today i've released the v0.8.0 that should contains the changes you need to work on v1.5+

**Comment by Vogliadicone** [comment]
Thanks, I've just updated to  v0.8.0.

**Comment by steveculshaw** [comment]
Thanks also ... updated to v0.8.0 and core 1.5.2 and all working again
