### ISSUE TITLE
Can't update from 0.1 to 0.5

### ISSUE THREAD

**Issue by Vogliadicone** [mrcomac/token-action-hud-swade#3]
FVTT tells me there is a new Update 0.5:
![TAH1](https://github.com/mrcomac/token-action-hud-swade/assets/119852651/8ac4d342-7d0a-4fbc-b0b9-f1e54c9002df)
But when I change to the new manifest url, FVTT still uses 0.1:
![TAH2](https://github.com/mrcomac/token-action-hud-swade/assets/119852651/84735d25-ca06-44ae-879a-0008df11f3b6)

Even if I manually install this manifest url:
https://github.com/mrcomac/token-action-hud-swade/releases/download/0.5/module.json
I stay at 0.1...

- Token Action HUD Core: 1.4.9
- Token Action HUD SWADE: 0.1
- Swade System: 3.0.4
- Foundry VTT: 11.302
- Browser: Google Chrome

**Comment by mrcomac** [comment]
@Vogliadicone 
that is a typo in the version number. 
I've changed this in version 0.5.1.

Please update the module version.

**Comment by Vogliadicone** [comment]
Thanks, worked like a charm!

**Comment by mrcomac** [comment]
Thank you @Vogliadicone 
Feel free to open a new issue if needed. I just released this, There is a plan to add all functionalities from the classic to this new one.
