### ISSUE TITLE
[ENH] Token HUD for Vehicles?

### ISSUE THREAD

**Issue by Vogliadicone** [mrcomac/token-action-hud-swade#32]
Right now I'm using for the first time a vehicle in my game and just realized, that it isn't supportet by the Token Action HUD. It has a Driver assigned and some vehicle weapons. I would like to be able to do a maneuver check and use the vehicle weapons from the HUD.

Would that be possible? I know that the SWADE system want to redo the vehicle sheet after the release of FVTT12 in the [v4.0 Actor Sheet Overhauls update](https://gitlab.com/peginc/swade/-/milestones/82#tab-issues), so if it's not possible to support vehicles right now, it might be under FVTT12 and SWADE4...

- Foundry VTT: 11.315
- Swade System: 3.2.5
- Token Action HUD Core 1.5.2
- Token Action HUD SWADE 0.9.3
- Browser: Google Chrome

**Comment by mrcomac** [comment]
Hi,
i`ll look into this

**Comment by mrcomac** [comment]
version 0.9.4 added support to row maneuver checks and use the weapons in the vehicle (due to the limitation the token hud is copying the weapon to the sheet of the driver and removing it right after call the roll item. it might cause some issues with BR2)
