### ISSUE TITLE
Help Me menu items show multiple chat cards

### ISSUE THREAD

**Issue by bloy** [mrcomac/token-action-hud-swade#37]
**Describe the bug**
When any of the Help Me menu items are selected, the appropriate chat card appears many times.

**Steps to reproduce**
1. select a token
2. Click on 'Help Me' > 'Aim'
3. Count the new 'Aim' chat cards in the chat sidebar

**Versions:**
- Token Action HUD Core: 1.5.2
- Token Action HUD SWADE: 1.0.1
- Swade System: 3.3.11
- Foundry VTT: 11.315
- Browser: Firefox

**Additional context**
This happened when testing as a GM and as a player in a game.

**Comment by mrcomac** [comment]
It should be fixed in version 1.0.2

**Comment by bloy** [comment]
Confirmed fixed. Thank you.
