### ISSUE TITLE
v12 deprecation warnings

### ISSUE THREAD

**Issue by ddbrown30** [mrcomac/token-action-hud-swade#39]
You are accessing SwadeActiveEffect#icon which has been migrated to SwadeActiveEffect#img

![Screenshot 2024-07-05 132920](https://github.com/mrcomac/token-action-hud-swade/assets/9253904/943b1f75-4ebc-4b86-b25f-173b4330a997)

**Comment by mrcomac** [comment]
this is a message in v12, there is no swade for v12 yet. I'm waiting for the swade v4.0 to work on the hud for v12.

**Comment by mrcomac** [comment]
oh! there is a v12 swade compatible.

**Comment by ddbrown30** [comment]
Yeah, released yesterday. They also released a dev version of 4.0 like a month ago for module devs to get a head start. You can join the League Discord server if you want access to stuff like that. https://discord.gg/MmDURf9bj6

**Comment by mrcomac** [comment]
yep, i downloaded and it wasn't working very well that time, for this reason i decided to wait for a prod version

**Comment by mrcomac** [comment]
version 1.2.0 adds support to swade v4
