### ISSUE TITLE
Different roll behaviour in Token Action HUD Classic & Token Action HUD SWADE

### ISSUE THREAD

**Issue by Vogliadicone** [mrcomac/token-action-hud-swade#4]
I'm not sure, if it's a bug or intended and if it's a bug, it's for you or for SWADE Tools. But let's see...

If I use the old Token Action HUD Classic with SWADE and click on a weapon, it opens the roll dialog from SWADE Tools (which I use):
![TAH_old_1](https://github.com/mrcomac/token-action-hud-swade/assets/119852651/f5df4693-581b-4e8c-a787-c7848ae675cb)

But when I use the new Token Action HUD Core with Token Action HUD SWADE, it places the standard roll dialog of the SWADE system into the chat (above the roll with the old Token Action HUD Classic & SWADE Tools):
![TAH_new_1](https://github.com/mrcomac/token-action-hud-swade/assets/119852651/63469f9e-a655-4c4f-8d2e-63e4429ae0b7)

Since I prefer to use SWADE Tools: Can I change the behaviour? Or is this something that would have to be done by the Token Action HUD SWADE? Or can the SWADE Tools influence the roll (in that case I would open a ticket for SWADE Tools)?

- Token Action HUD Core: 1.4.9
- Token Action HUD SWADE: 0.5.1
- Swade System: swade 3.0.4
- SWADE Tools: 1.13.0
- Foundry VTT: 11.302
- Browser: Google Chrome

**Comment by mrcomac** [comment]
@Vogliadicone looks like I need to add support to SWADE Tools in this new version.
The new version doesn't support swade tools or better rolls. I'll add this request to the sprint. probably in the next update the support will be available.

I'll keep this open for tracking proposal

**Comment by mrcomac** [comment]
asked to swade tools maintainer to allow call rolls to that module. another option is swade tools changes their internall bind function (it might broke compatibility to token hud classic and might increase the tshirt size to maintain that specific function)

is pending a feedback from they

https://github.com/lipefl/swade-tools/issues/230

**Comment by Vogliadicone** [comment]
Thanks, works with v0.6.1 like a charm!

**Comment by Vogliadicone** [comment]
Thanks, works with v0.6.1 like a charm!
