### ISSUE TITLE
Ammo for weapons is being deducted from the actor, rather than the token, for non-linked tokens.

### ISSUE THREAD

**Issue by sroakjp** [mrcomac/token-action-hud-swade#42]
**Describe the bug**
When using the HUD to make a ranged attack for a non-linked token the ammo is not deducted from the token's ammo inventory, but from the ammo of the actor.

**Steps to reproduce**
1. Select a token that is not linked to the associated actor.
2. Click on weapons
3. Choose a ranged weapon with ammo
4. Make the attack roll
5. The ammo counter for the actor will change, but not for the token.

**Versions:**
- Token Action HUD Core: [e.g. 1.5.6]
- Token Action HUD SWADE: [e.g. 1.2.0]
- Swade System: [e.g. swade 4.1.0]
- Foundry VTT: [e.g. 12 build 331]
- Browser: [e.g. Google Chrome 127.0.6533.120]

**Additional context**
Note: Not sure if the issue lies with Token Action HUD SWADE, or Token Action HUD Core. Using the module with SWADE, so putting the issue here. If the issue is with Core we can create the issue there and close this one.
Also Note: The issue only occurs when initiating the attack from the HUD. Initiating the attack from the token sheet works as expected, implying the issue is with how the HUD is activating the roll card.

**Comment by sroakjp** [comment]
Update: Appears to be working as expected with latest version (2.0.0).

**Comment by mrcomac** [comment]
Thanks for the update @sroakjp 

I still need to review the code to make sure i'm using the references to the token and not to the actor itself.

I'll probably do some rework in the logic to fix any other issues and make this hud better.
