### ISSUE TITLE
Compatibility with Token Action Hud Core 2.04

### ISSUE THREAD

**Issue by Fritz4012** [mrcomac/token-action-hud-swade#44]
I expect you are already working on it but, the current SWADE version is not compatible with the latest (2.04) version of the Token Action Hud Core.

**Comment by mrcomac** [comment]
there will be a release by the end of the week (saturday).

There are no changes in the system HUD, only the enhanced v2 added by the core.

**Comment by mrcomac** [comment]
Compatibility to HUD core 2 has been released
