### ISSUE TITLE
Possible Freezing issue

### ISSUE THREAD

**Issue by Drone4416** [mrcomac/token-action-hud-swade#45]
**Describe the bug**
When selecting a token with a large number of edges/effects it causes the server/application to freeze up 

**Steps to reproduce**
1. Select a token with a large amount of stuff on it. Current test token has about 40 Edges and 20ish effect from things like those edges. 

**Versions:**
- Token Action HUD Core: Current as of 12/15/2024
- Token Action HUD SWADE: Current as of 12/15/2024
- Swade System: Current as of 12/15/2024
- Foundry VTT: Current Stable 12 as of 12/15/2024
- Browser: I'm using the local application but a player tested it and they were using some version of Chrome

**Additional context**
I wouldn't have even ran into this if this wasn't such a long campaign. This may also be related to another issue I will be submitting after this where custom images aren't showing on the HUD but I figured I should submit this separate just to be safe

**Comment by mrcomac** [comment]
can you please export that actor and post here?

**Comment by Drone4416** [comment]
[fvtt-Actor-samuro-6XsFdqYNcVFdsq1p.json](https://github.com/user-attachments/files/18154404/fvtt-Actor-samuro-6XsFdqYNcVFdsq1p.json)

**Comment by mrcomac** [comment]
for some reason that character was resulting in a list of 33,554,432 effects :sweat_smile:. 
The release 2.0.3 should solve this issue.
