### ISSUE TITLE
BR2 support not working with Powers

### ISSUE THREAD

**Issue by steveculshaw** [mrcomac/token-action-hud-swade#5]
**Describe the bug**
The HUD is triggering the core SWADE card when triggering a power ...
<img width="232" alt="image" src="https://github.com/mrcomac/token-action-hud-swade/assets/64320/86727383-fc1f-48c0-b0db-9eafb6d78073">

rather than the BR2 card ...
<img width="227" alt="image" src="https://github.com/mrcomac/token-action-hud-swade/assets/64320/700ef8e3-8289-4c2e-94e6-136e136771ac">

**Steps to reproduce**
1. Go to HUD
2. Click on a power
3. Check the Chat tab

**Versions:**
- Token Action HUD Core: [1.4.9]
- Token Action HUD SWADE: [0.5.1]
- Swade System: [3.0.4]
- Foundry VTT: [11.302]
- Browser: [Google Chrome 114.0.5735.134]

**Additional context**
N/A

**Comment by mrcomac** [comment]
Hi @steveculshaw,

Thank you,

I'm already awere about that.

I'm waiting BR2 developer  give a feedback on this ticket 
 https://github.com/javierriveracastro/betteroll-swade/issues/598

After that I'll make the required changes to support BR2. For now this task is blocked.

I'll keep this open for tracking proposal
