### ISSUE TITLE
ENH: Show Running in Token Action HUD

### ISSUE THREAD

**Issue by Vogliadicone** [mrcomac/token-action-hud-swade#6]
The old Token Action HUD had the running die under Attributes, allowing you to run easily (here with the running dialog from SWADE Tools):
![TAHUD_OLD](https://github.com/mrcomac/token-action-hud-swade/assets/119852651/9c1e1f46-be6a-445c-9d6c-cd8c271ad3e0)

In the new Token Action HUD for SWADE the running die is missing:
![TAHUD_NEW](https://github.com/mrcomac/token-action-hud-swade/assets/119852651/44d485ca-535f-4027-a9d2-601786b1adb2)

I would love to see the running die integrated again in the new Token Action HUD. But I'm not sure, what would be the best location for it: under Attributes like in the old version or under Actions. I feel like Action would be the better location.

- Token Action HUD Core: 1.4.9
- Token Action HUD SWADE: 0.6.1
- Swade System: swade 3.0.4
- SWADE Tools: 1.13.2
- Foundry VTT: 11.302
- Browser: Google Chrome

**Comment by steveculshaw** [comment]
Seconded 

I'd replicate the original and have it under Attributes as a "Derived Stats" entry

**Comment by mrcomac** [comment]
I'll add this to attributes in the next version. we always can revisitated categories and change its elements.

**Comment by Vogliadicone** [comment]
Or maybe place it within the general category. Since running is not based on attributes (like toughness) but only on the race and edges / hindrances, that would IMO also work. But we could also discuss this again later, when the new HUD is complete…

**Comment by steveculshaw** [comment]
Tried it out on player and monster tokens ... worked fine
