### ISSUE TITLE
ENH: Delete category "General"

### ISSUE THREAD

**Issue by Vogliadicone** [mrcomac/token-action-hud-swade#7]
As a GM I like a slim Token Action HUD for me and my players. Therefore I'm wondering if the category "General" is really needed. It shows only the Bennies:
![General](https://github.com/mrcomac/token-action-hud-swade/assets/119852651/2c9e2eec-d9f4-45e0-92eb-f85c82653ce8)

But the Bennies could IMO also be shown under "Actions". I know, that spending a Benny in SWADE isn't strictly an Action. But it feels more like an Action, than a General thingy. No idea, how you or others think about it, but I would prefer a slightly slimer set up without the "General" option.

- Token Action HUD Core: 1.4.9
- Token Action HUD SWADE: 0.6.1
- Swade System: 3.0.4
- Foundry VTT: 11.302
- Browser: Google Chrome

**Comment by mrcomac** [comment]
Hi @Vogliadicone ,

Spend a benny is an action however, action in the HUD are those actions within the action tab.

It means, all items within the action tab will be available on the "Action" category. General category is to have other elements that don't have categories within the sheet.

Feel free to push back this idea. we can discuss on this thread and find an agreement.

**Comment by Vogliadicone** [comment]
Yeah, maybe it’s better to add all the missing elements from the old Token Action HUD first and maybe some new elements, if somebody comes up with an Enhancement, and then think about the reorganisation afterwards…

**Comment by Larkinabout** [comment]
You can also move groups and actions around on the HUD, so you could move the Benny group wherever you want. Check out the wiki on adding and removing groups: [How to Use Token Action HUD](https://github.com/Larkinabout/fvtt-token-action-hud-core/wiki/How-to-Use-Token-Action-HUD).

**Comment by Vogliadicone** [comment]
> You can also move groups and actions around on the HUD, so you could move the Benny group wherever you want.

I tried that, but it didn't work. Not sure, if it's an issue for core or SWADE, but after I added "Running" to the "Skills" category, all the skills showed up 2 times:
![TAHUD_1](https://github.com/mrcomac/token-action-hud-swade/assets/119852651/fad02d33-0ad0-456e-b0e3-faededa594ff)
When I tried to edit the options, I saw for a moment a second "skills" category, 
![TAHUD_2](https://github.com/mrcomac/token-action-hud-swade/assets/119852651/97eddd90-c97c-4d90-a164-80880acacd74)
And a second later it looked like this:
![TAHUD_3](https://github.com/mrcomac/token-action-hud-swade/assets/119852651/0813dfe9-4469-40a3-8734-696fc347cfa7)

Only the "Reset HUD" seems to solve it.

I also realiceds, that a lot of categories have the same name. F.e. I got 6x "Group: Quick Access", which makes it not easy to choose the right one...

- Token Action HUD Core: 1.4.11
- Token Action HUD SWADE: 0.7.0
- Swade System: 3.0.4
- Foundry VTT: 11.304
- Browser: Google Chrome

**Comment by Vogliadicone** [comment]
Thanks for all your changes in the HUD! Just to let you know (and so that this issue can be closed), I updated to 0.7.2 and reseted the HUD via the "Reset HUD" option:
- I can now delete mayou categories ( i just can't delete categories within a category, but I opened an [new ticket](https://github.com/mrcomac/token-action-hud-swade/issues/15) for that)
- The problems with some categories showing up 2x seems to be solved
- The problem that some categories have the same name (f.e. I got 6x "Group: Quick Access") seems to be solved
