### ISSUE TITLE
Show Wounds/Fatigue in Token Action HUD

### ISSUE THREAD

**Issue by steveculshaw** [mrcomac/token-action-hud-swade#9]
**Is your feature request related to a problem? Please describe.**
The old Token Action HUD had a section for Wounds/Fatigue allowing you to easily add/subtract wounds & fatigue 

<img width="169" alt="image" src="https://github.com/mrcomac/token-action-hud-swade/assets/64320/b848a7b6-6926-4ec9-9486-4ab7701e3687">

**Describe the solution you'd like**
It would be really useful to replicated this into the new Token Action HUD SWADE modules.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

Additional context
OS: [Windows 11]
Token Action HUD: [1.4.9]
Token Action HUD SWADE: [0.6.1]
Swade System: [3.0.4]
Foundry VTT: [11.302]
Browser: [Google Chrome 114.0.5735.134]
Other modules: BR2

**Comment by Vogliadicone** [comment]
But I wouldn't call the section "Wounds/Fatigue", that's IMO too long. I would call it "Health" or add both options to the "General" section.

**Comment by mrcomac** [comment]
I'll check that. Thank you for opening this issue.

**Comment by steveculshaw** [comment]
@mrcomac Updated to v0.7.0, but I'm not seeing anything w.r.t. token wounds?

Does something need to be activated?

**Comment by steveculshaw** [comment]
@mrcomac 
Ignore me ... I read through some of the other issues, and spotted the comment about the difference between Reset HUD (which is in the HUD Core settings) and the Reset Actions (which is in the SWADE HUD bar options)
